### ISSUE TITLE
Account test

### ISSUE THREAD

**Issue by hoangg04** [poin4003/momo_payment_golang#1]
Bác cho em hỏi, bác có test được bằng account test không?

**Comment by poin4003** [comment]
> Bác cho em hỏi, bác có test được bằng account test không?

Có nha, cứ bật server lên rồi vô file momo.http request là nó ra url momo, xong rồi dùng momo uat để quét mã là ok.

**Comment by hoangg04** [comment]
Momo uat mình bắt kyc ấy. Có cách nào để pass qua kyc ko bác

**Comment by poin4003** [comment]
> Momo uat mình bắt kyc ấy. Có cách nào để pass qua kyc ko bác

Bạn cứ nhập sđt linh tinh vào, kiểu 092222333, otp hay pass đều là 00000 hết

**Comment by hoangg04** [comment]
à mình biết cái đấy nhưng nó khi kyc để nạp tiền test đấy. Nó yêu cầu kyc @@

**Comment by poin4003** [comment]
> à mình biết cái đấy nhưng nó khi kyc để nạp tiền test đấy. Nó yêu cầu kyc @@

À, momo mới bữa nay bắt làm xác thực, mình mới test lại, cũng ko xác thực được, hình như bên momo đang lỗi khúc đó

**Comment by hoangg04** [comment]
cám ơn bác nhé
